export type Data = {
  id: number;
  nombre: string;
  apellido: string;
  email: `${string}@${string}.${string}`;
  pais: string;
}

export const datos: Data[] = [
  {
    id: 1,
    nombre: "Juan",
    apellido: "Pérez",
    email: "JuanPerez@gmail.com",
    pais: "Argentina",
  },
  {
    id: 2,
    nombre: "María",
    apellido: "Gómez",
    email: "Maria@outlook.com",
    pais: "Brasil",
  },
  {
    id: 3,
    nombre: "Federico",
    apellido: "Martínez",
    email: "pp@photmail.com",
    pais: "Perú",
  },
  {
    id: 4,
    nombre: "Ana",
    apellido: "López",
    email: "ana@gmail.com",
    pais: "Chile",
  },
  {
    id: 5,
    nombre: "Carlos",
    apellido: "Sánchez",
    email: "carlos@hotmail.com",
    pais: "México",
  },
  {
    id: 6,
    nombre: "Laura",
    apellido: "Fernández",
    email: "laura@yahoo.com",
    pais: "Colombia",
  },
  {
    id: 7,
    nombre: "Pedro",
    apellido: "García",
    email: "pedro@gmail.com",
    pais: "Uruguay",
  },
  {
    id: 8,
    nombre: "Lucía",
    apellido: "Rodríguez",
    email: "lucia@outlook.com",
    pais: "Paraguay",
  },
  {
    id: 9,
    nombre: "Miguel",
    apellido: "Hernández",
    email: "miguel@hotmail.com",
    pais: "Venezuela",
  },
  {
    id: 10,
    nombre: "Sofía",
    apellido: "Martín",
    email: "sofia@yahoo.com",
    pais: "Ecuador",
  },
  {
    id: 11,
    nombre: "Jorge",
    apellido: "Ruiz",
    email: "jorge@gmail.com",
    pais: "Bolivia",
  },
  {
    id: 12,
    nombre: "Elena",
    apellido: "Díaz",
    email: "elena@outlook.com",
    pais: "Panamá",
  },
  {
    id: 13,
    nombre: "Raúl",
    apellido: "Morales",
    email: "raul@hotmail.com",
    pais: "Costa Rica",
  },
  {
    id: 14,
    nombre: "Marta",
    apellido: "Jiménez",
    email: "marta@yahoo.com",
    pais: "Honduras",
  },
  {
    id: 15,
    nombre: "Luis",
    apellido: "Ortiz",
    email: "luis@gmail.com",
    pais: "Guatemala",
  },
  {
    id: 16,
    nombre: "Andrés",
    apellido: "Castro",
    email: "andres@gmail.com",
    pais: "Argentina",
  },
  {
    id: 17,
    nombre: "Valeria",
    apellido: "Mendoza",
    email: "valeria@outlook.com",
    pais: "Brasil",
  },
  {
    id: 18,
    nombre: "Diego",
    apellido: "Silva",
    email: "diego@hotmail.com",
    pais: "Perú",
  },
  {
    id: 19,
    nombre: "Paula",
    apellido: "Ramos",
    email: "paula@yahoo.com",
    pais: "Chile",
  },
  {
    id: 20,
    nombre: "Ricardo",
    apellido: "Romero",
    email: "ricardo@gmail.com",
    pais: "México",
  },
  {
    id: 21,
    nombre: "Natalia",
    apellido: "Vargas",
    email: "natalia@outlook.com",
    pais: "Colombia",
  },
  {
    id: 22,
    nombre: "Santiago",
    apellido: "Torres",
    email: "santiago@hotmail.com",
    pais: "Uruguay",
  },
  {
    id: 23,
    nombre: "Gabriela",
    apellido: "Flores",
    email: "gabriela@yahoo.com",
    pais: "Paraguay",
  },
  {
    id: 24,
    nombre: "Manuel",
    apellido: "Acosta",
    email: "manuel@gmail.com",
    pais: "Venezuela",
  },
  {
    id: 25,
    nombre: "Isabel",
    apellido: "Herrera",
    email: "isabel@outlook.com",
    pais: "Ecuador",
  },
  {
    id: 26,
    nombre: "Francisco",
    apellido: "Medina",
    email: "francisco@hotmail.com",
    pais: "Bolivia",
  },
  {
    id: 27,
    nombre: "Claudia",
    apellido: "Soto",
    email: "claudia@yahoo.com",
    pais: "Panamá",
  },
  {
    id: 28,
    nombre: "Hugo",
    apellido: "Suárez",
    email: "hugo@gmail.com",
    pais: "Costa Rica",
  },
  {
    id: 29,
    nombre: "Patricia",
    apellido: "Rojas",
    email: "patricia@outlook.com",
    pais: "Honduras",
  },
  {
    id: 30,
    nombre: "Alberto",
    apellido: "Ortega",
    email: "alberto@hotmail.com",
    pais: "Guatemala",
  },
  {
    id: 31,
    nombre: "Daniela",
    apellido: "Guzmán",
    email: "daniela@yahoo.com",
    pais: "Argentina",
  },
  {
    id: 32,
    nombre: "Javier",
    apellido: "Paredes",
    email: "javier@gmail.com",
    pais: "Brasil",
  },
  {
    id: 33,
    nombre: "Rosa",
    apellido: "Peña",
    email: "rosa@outlook.com",
    pais: "Perú",
  },
  {
    id: 34,
    nombre: "Fernando",
    apellido: "Cabrera",
    email: "fernando@hotmail.com",
    pais: "Chile",
  },
  {
    id: 35,
    nombre: "Alicia",
    apellido: "Campos",
    email: "alicia@yahoo.com",
    pais: "México",
  },
  {
    id: 36,
    nombre: "Martín",
    apellido: "Reyes",
    email: "martin@gmail.com",
    pais: "Colombia",
  },
  {
    id: 37,
    nombre: "Verónica",
    apellido: "Aguilar",
    email: "veronica@outlook.com",
    pais: "Uruguay",
  },
  {
    id: 38,
    nombre: "Gustavo",
    apellido: "Molina",
    email: "gustavo@hotmail.com",
    pais: "Paraguay",
  },
  {
    id: 39,
    nombre: "Silvia",
    apellido: "Ortiz",
    email: "silvia@yahoo.com",
    pais: "Venezuela",
  },
  {
    id: 40,
    nombre: "Roberto",
    apellido: "Delgado",
    email: "roberto@gmail.com",
    pais: "Ecuador",
  },
  {
    id: 41,
    nombre: "Carmen",
    apellido: "Figueroa",
    email: "carmen@outlook.com",
    pais: "Bolivia",
  },
  {
    id: 42,
    nombre: "Mario",
    apellido: "Espinoza",
    email: "mario@hotmail.com",
    pais: "Panamá",
  },
  {
    id: 43,
    nombre: "Adriana",
    apellido: "Navarro",
    email: "adriana@yahoo.com",
    pais: "Costa Rica",
  },
  {
    id: 44,
    nombre: "Felipe",
    apellido: "Vega",
    email: "felipe@gmail.com",
    pais: "Honduras",
  },
  {
    id: 45,
    nombre: "Lorena",
    apellido: "Cruz",
    email: "lorena@outlook.com",
    pais: "Guatemala",
  },
];
